version: '2'
services:
  postgres-server:
    image: postgres:14.0
    restart: always
    container_name: zabbix-db
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix-bdd-password
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /apps/zabbix/db:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    restart: always
    container_name: zabbix
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix-bdd-password
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_STARTVMWARECOLLECTORS: 10
      ZBX_VMWAREFREQUENCY: 30
      ZBX_VMWAREPERFFREQUENCY: 30
      ZBX_VMWARECACHESIZE: 16M
      ZBX_VMWARETIMEOUT: 10
    depends_on:
      - postgres-server
    ports:
      - 10051:10051
    volumes:
      - /apps/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: always
    container_name: zabbix-web
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix-bdd-password
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Paris"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 8090:8080

version: '2'
services:
   zabbix-agent:
      image: zabbix/zabbix-agent:latest
      restart: always
      environment:
        ZBX_HOSTNAME: Zabbix server
        ZBX_SERVER_HOST: 127.0.0.1
      ports:
        - 10050:10050
      volumes:
        - /apps/zabbix/agent:/var/lib/zabbix/enc

