version: '2'
services:
  postgres-server:
    image: postgres:14.0
    restart: always
    container_name: zabbix-db
    environment:
      POSTGRES_USER: usrzabbix
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: db_zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /apps/zabbix/db:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    restart: always
    container_name: zabbix
    environment:
      POSTGRES_USER: usrzabbix
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: db_zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_STARTVMWARECOLLECTORS: 10
      ZBX_VMWAREFREQUENCY: 30
      ZBX_VMWAREPERFFREQUENCY: 30
      ZBX_VMWARECACHESIZE: 16M
      ZBX_VMWARETIMEOUT: 10
    depends_on:
      - postgres-server
    ports:
      - 10051:10051
    volumes:
      - /apps/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: always
    container_name: zabbix-web
    environment:
      POSTGRES_USER: usrzabbix
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: db_zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Paris"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 8090:8080
